server:
  port: 8081
  servlet:
    context-path: /stock
spring:
  ## 此配置用来解决spring和swagger的冲突问题
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.159.1:8848
        username: nacos
        password: nacos
  profiles:
    active: dev
  application:
    name: stock

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
## mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml